### ISSUE TITLE
where artifacts?

### ISSUE THREAD

**Issue by sf105** [jmock-developers/jmock-packaging#3]
We push artifacts to https://dav.codehaus.org/repository/jmock/ authenticated using WebDAV. Would you prefer to publish to Github / remove all dependencies to Codehaus?

**Comment by sf105** [comment]
yes. Move to github completely

**Comment by tobyweston** [comment]
You could run a Maven repository straight from Github which makes deployment super lightweight (just a gut push to gh_pages). Downside is that Maven central won't pick it up....

**Comment by sf105** [comment]
I think it really has to get into maven central, so that people don't depend on our repo.

S

**Comment by mprins** [comment]
@tobyweston imo that would be a problem, I've had problems with a repo hosted in gh-pages before, it turned out these were just too big. 
Also in an enterprise environment you just don't want to keep on adding repository locations to your maven proxy, it gets unmaitainable.

Sonatype has a detailed descriptionon how to get stuff into central; see: https://docs.sonatype.org/display/Repository/Sonatype+OSS+Maven+Repository+Usage+Guide

**Comment by tobyweston** [comment]
We can close this one. Decision was to move everything from Codehaus including publishing artifacts which will be done via Sonatype (see [Issue 12](https://github.com/jmock-developers/jmock-library/issues/12) of the jmock-library project)
